version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: 
          command: touch src/__init__.py
          name: Initializing /src as Python Module

      - run:
          command: mv src/Strategies strategies 
          name: Renaming strategies :)
      - run:
          command: python3 -m pytest test*.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
