version: 2.1
parameters:
  image-tag:
    type: string
    default: "latest"
orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: touch src/__init__.py && echo $<< pipeline.parameters.image-tag >>
          name: Initializing /src as Python Module

      - run:
          command: mv src/Strategies src/strategies
          name: Renaming Strategies
      - run:
          command: python3 -m pytest tests.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
