version: "3.5"

services:
  proto_uploader:
    container_name: proto_uploader
    build:
      context: ../../
      dockerfile: ops/protohook/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ~/.gitconfig:/etc/gitconfig
  